### ISSUE TITLE
How to talk to project owner?

### ISSUE THREAD

**Issue by Countryman98** [amnesica/BelugaProject#1]
I have tried installing this multiple times as described on Ubuntu 20.04 with no Luck. I currently run another Flight-tracking website with ten of thousands of planes and would really like to put beluga to the test as it looks like i software that i might to be keen to replace my current software with. Sorry for posting in this area but i'm fairly new to github and dont know how to contact project owners.

Any chance of a tutorial or install instruction to install on Ubuntu 20.04?

Would very much appreciate it!
Best of Regard's,
http://flight-tracker.nz

**Comment by amnesica** [comment]
Hi Countryman98,

thanks for your interest in the project!
We are currently working on an improved version and will probably release it at the end of the year. The new manual will have instructions for an installation on debian based systems like ubuntu. 

Best regards,
amnesica

**Comment by amnesica** [comment]
Hi Countryman98,

the new version of the Beluga Project is finally released. The manual provides instructions for Ubuntu 20.04 as well. You might want to try it out.

Best regards,
amnesica

**Comment by Countryman98** [comment]
Hi Amnescia, Have installed and running on Ubuntu 20.04 (HP Gen 8 Server) and am liking what i see.
I however do currently use Virtual Radar Server and have many feeders that don't use AircraftList.json format feeds.
I would love to be able to have Beluga pull a feed from Virtual Radar Server AircraftList.json or Basestation formats. 

Is it possible to add support for Either of the 2x options above? Appreciate your software and your help!

Please close "Issue 1" and i posted it in the wrong place then found i could delete it.. lol
Best of Regard's,
Countryman98
