### ISSUE TITLE
Aircraft Stats (speed,height) not showing

### ISSUE THREAD

**Issue by rikgale** [amnesica/BelugaProject#13]
Hello.
I have just installed the BelugaProject on one of my pi as a test
I am feeding from a local tar1090 instance and I am seeing aircraft on the screen. I believe that I've set up the feed correctly in the .env

![image](https://github.com/amnesica/BelugaProject/assets/66202012/c2027b89-bc92-4c0b-bbd9-9f28d5c508bd)

Please can you advise, as I expect that I have done something wrong.
Many thanks

**Comment by amnesica** [comment]
Hi @rikgale,
thanks for trying out the project. Can you provide us the full aircraft.json from your feeder and your .env file (without any sensitive information) here? I'm running tar1090 as well and don't have issues so far.

**Comment by amnesica** [comment]
@rikgale After looking again at your screenshot, try using "adsbx" instead of "tar1090" as your feeder type in your .env file. The feeder type "tar1090" does not exist.

**Comment by rikgale** [comment]
I'll try that.

**Comment by rikgale** [comment]
I changed the type to adsbx as feeder type and I get no aircraft on screen. Oddly enough when I change it back to tar1090 I also get no aircraft now either.

My json output can be seen [here](http://cornwallvrs.com/tar1090/data/aircraft.json)

This is the same source as the local ip address shown above.

docker logs for server - https://termbin.com/cap7
docker logs for webapp - https://termbin.com/r66l
docker logs for postgres - https://termbin.com/b7ii  

My .env file

`
LOCATION_LATITUDE=5x.xx
LOCATION_LONGITUDE=-4.xx
FEEDER_IP=http://192.168.1.3/tar1090/data/aircraft.json
FEEDER_TYPE=adsbx
FEEDER_NAME=Home
FEEDER_COLOR=red
FEEDER_AMOUNT=1
SCALE_ICONS=1.0
CIRCLE_DISTANCE_OF_RINGS=50,100,150,200
SEARCH_ENGINE_URL=https://www.startpage.com/sp/search?language=english&t=default&lui=english&query=aircraft+photo+<PLACEHOLDER>&cat=images
LOGGING_FILE_NAME=.local/share/applications/BelugaProject/logfiles/BelugaProject.log
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/belugaDb
SPRING_DATASOURCE_USERNAME=beluga
SPRING_DATASOURCE_PASSWORD=belugaDb
POSTGRES_DB=belugaDb
OPENSKY_NETWORK_USERNAME=TODO
OPENSKY_NETWORK_PASSWORD=TODO
PROD_BASE_URL_WEBAPP=192.168.1.156
`
Apologies it has all come out as one line - ugh!

**Comment by amnesica** [comment]
Hi @rikgale,
thanks for all the info :) We've tested the json output with FEEDER_TYPE set to adsbx the following appears in the browser:

![image](https://github.com/amnesica/BelugaProject/assets/54629966/5a444274-2ccf-4e0f-b714-3bf6136b7739)

So we don't think that there's an issue with the .env file or the FEEDER_TYPE. However, one possibility is that the docker images were not build properly after changing the .env file.

What you can try is the following:
* Open a terminal in your pi's BelugaProject directory 
* Stop and remove all containers with `./run.sh docker-rm`
* Run `./run.sh install` again

Btw impressive range!! :)

**Comment by rikgale** [comment]
That is the combined feed from 6 feeders - so not quite as impressive as it looks.

The removal was successful the I ran `./run.sh install`

but...

```
pi@raspberrypi:~/BelugaProject-master $ ./run.sh install
Install the Beluga Project ...
Gentle reminder: Have you configured the values in the .env file (y/n)?y
-> Yes, let's continue ...
Run the containers in the background ...
[+] Running 3/3
 ! webapp Warning                                                                                                                                                        6.5s
 ✘ postgres Error                                                                                                                                                        7.6s
 ! server Warning                                                                                                                                                        5.7s
Error response from daemon: Head "https://registry-1.docker.io/v2/library/postgres/manifests/13.1-alpine": EOF
```

**Comment by rikgale** [comment]
I tried again this morning and it all installed ok. However still no aircraft on screen.

I checked the logs of the postgres container - https://termbin.com/bv62

Seems to start with a syntax error and go down hill from there.

If it is of any value I am running on a Pi 5 on the official Raspberry Pi OS using docker installed using the SDR-Enthusiasts script to install docker https://github.com/sdr-enthusiasts/docker-install which has never given me any problems to date which I used on all my feeders, my server and my NAS box.

**Comment by rikgale** [comment]
I've just tried doing a ```./run.sh load-db``` followed by a ```./run.sh update-db``` and I would now appear to have aircraft on the screen. 
No idea why that would have worked, but it has. Now to keep poking it.

The Altitude and Speed etc that I was having problems with before now appear to be showing for all aircraft, but the aircraft information e.g. reg / type etc now appears to be missing for some, but not all aircraft. I have cross referenced a couple with the Opensky database on which your data source appears to be based and for the example below it is in the database as PH-BQF

![image](https://github.com/amnesica/BelugaProject/assets/66202012/4810d305-fd65-4aac-8b00-61e1ec3ce72c)

I'll let it run for a bit and see if the issue goes away.

I would like to say that I think this is a very nice piece of software and the USP for me is the Point of Minimum Distance - it's a fantastic idea

**Comment by rikgale** [comment]
It caught up with itself

**Comment by amnesica** [comment]
Hi @rikgale,
do you mean that it's working now? We're currently setting up a Raspberry Pi with your version to get a better understanding of the issue.

**Comment by rikgale** [comment]
Yes - it is working now :) After loading the containers and doing a `./run.sh load-db` followed by a `./run.sh update-db` It started working. The flights that were initially on the screen did not show information, but as new flights were added the aircraft information was correctly populated. 

I'm a bit loathed to restart it in case I break it, but going to have to at somepoint. Thank you for all your help!

**Comment by amnesica** [comment]
@rikgale Good to hear :) If you any other questions/issues feel free to reach out to us :)
