### ISSUE TITLE
Beluga Project behind ngnix reverse proxy

### ISSUE THREAD

**Issue by rikgale** [amnesica/BelugaProject#15]
Hello 
Do you have any guidance as to how to have this project running behind a reverse webproxy?
Currently all I am getting is... https://cornwallvrs.com/beluga/
I have added 
```
location /beluga/ {
    proxy_pass http://192.168.1.156:8090/;
}
```
to the locations.conf of my ngnix reverse proxy set up, but I am wondering if I need more to pass anything else, or  if I am missing some setting somewhere or do I need to change the `PROD_BASE_URL_WEBAPP` from `IP` to `IP/belgua`  e.g. 

```
PROD_BASE_URL_WEBAPP=192.168.1.156
```
to 
```
PROD_BASE_URL_WEBAPP=192.168.1.156/beluga
```
Many thanks

**Comment by amnesica** [comment]
@rikgale I'm afraid we cannot help you on this issue because we don't have experience publishing on the web. It would be amazing to see the project live on the web :) Hope you can fix the issue.

**Comment by rikgale** [comment]
Thanks for your honesty. I'll keep trying

**Comment by amnesica** [comment]
I'll close this issue for now.
