### ISSUE TITLE
Port 8080?

### ISSUE THREAD

**Issue by dg9bja** [amnesica/BelugaProject#21]
Hi, 
just wanted to test that project and after I run install.sh it could not start because port 8080 is already in use. I tought 8090 will be used for web service? Is 8080 used internally? Is it possible to change it anywhere?
Best regards
Ludger

**Comment by amnesica** [comment]
Hi Ludger,

thanks for trying out the project.

Port 8080 is used by the server while port 8090 is used by the webapp/frontend. I'm afraid at the moment its not possible to change the port as this needs some code changes. Do you already have a running application on port 8080?

Kind regards,
amnesica

**Comment by dg9bja** [comment]
Hi, 
thanks for that information. Yes I have already something running on that VM. Did not had many time but will check it again.
Best regards 
Ludger
