### ISSUE TITLE
Cannot invoke "java.lang.Double.doubleValue()" because the return value of "com.amnesica.belugaproject.config.Configuration.getLatFeeder()" is null

### ISSUE THREAD

**Issue by Maulik1528** [amnesica/BelugaProject#25]
Hi @amnesica,

Can you please help me resolving attached issue? 

> java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "com.amnesica.belugaproject.config.Configuration.getLatFeeder()" is null
> 	at com.amnesica.belugaproject.services.aircraft.AircraftService.setValuesToAircraft(AircraftService.java:476) ~[!/:4-0-0]
> 	at com.amnesica.belugaproject.services.aircraft.AircraftService.createNewRemoteAircraft(AircraftService.java:88) ~[!/:4-0-0]
> 	at com.amnesica.belugaproject.services.aircraft.OpenskyService.processOpenskyAircraftJsonArray(OpenskyService.java:80) ~[!/:4-0-0]
> 	at com.amnesica.belugaproject.services.aircraft.OpenskyService.fetchAircraftData(OpenskyService.java:63) ~[!/:4-0-0]
> 	at com.amnesica.belugaproject.services.aircraft.RemoteService.getPlanesFromRemote(RemoteService.java:73) ~[!/:4-0-0]
> 	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
> 	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.1.jar!/:6.1.1]
> 	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.1.jar!/:6.1.1]
> 	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.0.jar!/:1.12.0]
> 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.1.jar!/:6.1.1]
> 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.1.jar!/:6.1.1]
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
> 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]`

**Comment by amnesica** [comment]
Hi @Maulik1528, have you entered the values in the .env file as shown in the examples in the installer? The latitude value should be something like 12.3456 with a "." and not a ",". Maybe that is the issue.

Kind regards
amnesica

**Comment by Maulik1528** [comment]
Hi @amnesica,
Thank you for providing quick response and this awesome project.

I do not have any feeders and I want to plot planes by just using OpenSky-network data. Now LOCATION_LATITUDE and LOCATION_LONGITUDE from env file will be of my current location?

Thank you for helping me out.

Regards,
Maulik

**Comment by Maulik1528** [comment]
@amnesica ,

I have corrected the issue and you were right about it. Now it is working as expected. Thank you for helping out. I am closing this issue.

Warm Regards,
Maulik
