### ISSUE TITLE
Failed to determine a suitable driver class

### ISSUE THREAD

**Issue by Maulik1528** [amnesica/BelugaProject#26]
Hi @amnesica, 
As I am trying to run this outside the docker, it shows error for server as shown. Maybe there is an issue related to Database but as I am new to Spring, I am not able to figure it out. Please help me to resolve this error. Thanks in advance.

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
> 
> Reason: Failed to determine a suitable driver class
> 
> 
> Action:
> 
> Consider the following:
>         If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
>         If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
>

**Comment by amnesica** [comment]
Hi @Maulik1528,
running the Beluga Project outside of docker is not supported by us, sorry.
Hope you will get a fix.

Kind regards
amnesica
