### ISSUE TITLE
@amnesica can you give me some guidance please?

### ISSUE THREAD

**Issue by Countryman98** [amnesica/BelugaProject#3]
Hi Installed The Beluga Project and up is running nicely. Unfortunately i can only connect 2 feeders and use OpenSky.

Is there some other forums/platform where we can chat by Private Message and i can ask some questions please.

Im on discord, facebook take your pick.

Thanks

**Comment by amnesica** [comment]
Hi @Countryman98, please keep posting your questions as issues. Solved questions can then also help others who may have the same questions. We will try to answer them as quickly as possible.

**Comment by Countryman98** [comment]
Ok, thanks @amnesica. Can anyone help out with a config file to pull data from a Virtual Radar Server (VRS) AircraftList.json. Have it up and running but cant pull from Virtual Radar server.  Heres a snippet of the vrs AircraftList.json:

{"src":1,"feeds":[{"id":2,"name":"FT-ADS-B1","polarPlot":true},{"id":3,"name":"FT-ADS-B2","polarPlot":true},{"id":4,"name":"FT-AU","polarPlot":true},{"id":5,"name":"FT-FI","polarPlot":true},{"id":6,"name":"FT-FI2","polarPlot":true},{"id":7,"name":"FT-FI2-MLAT","polarPlot":true},{"id":8,"name":"FT-FI-MLAT","polarPlot":true},{"id":11,"name":"FT-MS","polarPlot":true},{"id":12,"name":"FT-SAT1","polarPlot":true},{"id":18,"name":"FT SATELLITE-1","polarPlot":true},{"id":19,"name":"FT SATELLITE-2","polarPlot":true},{"id":20,"name":"FT SATELLITE-3","polarPlot":true},{"id":21,"name":"FT SATELLITE-4","polarPlot":true},{"id":15,"name":"FEED - FAM - WORLD","polarPlot":false}],"srcFeed":15,"showSil":true,"showFlg":true,"showPic":true,"flgH":20,"flgW":85,"acList":[{"Id":10721086,"Rcvr":3,"HasSig":false,"Icao":"A3973E","Bad":false,"FSeen":"2022-02-26T12:50:33.638Z","CMsgs":2,"Alt":4450,"GAlt":4760,"InHg":30.2303143,"AltT":0,"Lat":26.53587,"Long":-81.688477,"PosTime":1645879833638,"Mlat":false,"Tisb":false,"Spd":239.0,"Trak":129.0,"TrkH":false,"IsFerryFlight":false,"IsCharterFlight":false,"Sqk":"","Vsi":4352,"VsiT":0,"WTC":0,"Species":0,"EngType":0,"EngMount":0,"Mil":false,"Cou":"United States","HasPic":false,"Interested":false,"FlightsCount":0,"SpdTyp":0,"CallSus":false,"Trt":2},{"Id":4546641,"Rcvr":3,"HasSig":false,"Icao":"456051","Bad":false,"FSeen":"2022-02-26T12:50:31.837Z","TSecs":2,"CMsgs":3,"Alt":0,"GAlt":169,"InHg":30.088583,"AltT":0,"Call":"TXLU19","Lat":42.565392,"Long":23.289909,"PosTime":1645879831838,"Mlat":false,"Tisb":false,"Spd":0.0,"TrkH":false,"IsFerryFlight":false,"IsCharterFlight":false,"Sqk":"","Vsi":0,"VsiT":0,"WTC":0,"Species":0,"EngType":0,"EngMount":0,"Mil":false,"Cou":"Bulgaria","HasPic":false,"Interested":false,"FlightsCount":0,"SpdTyp":0,"CallSus":false,"Trt":2},{"Id":4000387,"Rcvr":3,"HasSig":false,"Icao":"3D0A83","Bad":false,"FSeen":"2022-02-26T12:50:31.294Z","TSecs":3,"CMsgs":2,"Alt":2699,"GAlt":3310,"InHg":30.531496,"AltT":0,"Lat":49.340801,"Long":8.5655,"PosTime":1645879831294,"Mlat":false,"Tisb":false,"Spd":85.0,"Trak":94.0,"TrkH":false,"IsFerryFlight":false,"IsCharterFlight":false,"Sqk":"","Vsi":-149,"VsiT":0,"WTC":0,"Species":0,"EngType":0,"EngMount":0,"Mil":false,"Cou":"Germany","HasPic":false,"Interested":false,"FlightsCount":0,"SpdTyp":0,"CallSus":false,"Trt":2},{"Id":65760,"Rcvr":3,"HasSig":false,"Icao":"0100E0","Bad":false,"FSeen":"2022-02-26T12:50:30.346Z","TSecs":4,"CMsgs":3,"Alt":35000,"GAlt":35169,"InHg":30.088583,"AltT":0,"Call":"MSR920","Lat":29.479156,"Long":35.24826,"PosTime":1645879830349,"Mlat":false,"Tisb":false,"Spd":541.0,"Trak":75.0,"TrkH":false,"IsFerryFlight":false,"IsCharterFlight":false,"Sqk":"","Vsi":-448,"VsiT":0,"WTC":0,"Species":0,"EngType":0,"EngMount":0,"Mil":false,"Cou":"Egypt","HasPic":false,"Interested":false,"FlightsCount":0,"SpdTyp":0,"CallSus":false,"Trt":2},{"Id":4921366,"Rcvr":2,"HasSig":false,"Icao":"4B1816","Bad":false,"FSeen":"2022-02-26T12:50:29.741Z","TSecs":4,"CMsgs":1,"InHg":30.4429131,"AltT":0,"Call":"SWR41RF","Lat":47.4515,"Long":8.5599,"PosTime":1645879829741,"Mlat":false,"Tisb":false,"Spd":0.0,"Trak":185.6,"TrkH":false,"IsFerryFlight":false,"IsCharterFlight":false,"Sqk":"","Ident":false,"VsiT":0,"WTC":0,"Species":0,"EngType":0,"EngMount":0,"Mil":false,"Cou":"Switzerland","HasPic":false,"Interested":false,"FlightsCount":0,"Gnd":true,"SpdTyp":0,"CallSus":false,"Trt":2,"Sat":true},{"Id":4344291,"Rcvr":2,"HasSig":false,"Icao":"4249E3","Bad":false,"FSeen":"2022-02-26T12:50:29.715Z","TSecs":4,"CMsgs":1,"Alt":1425,"GAlt":1623,"InHg":30.11811,"AltT":0,"Call":"SBI2167","Lat":55.4306,"Long":37.8583,"PosTime":1645879829715,"Mlat":false,"Tisb":false,"Spd":177.5,"Trak":316.1,"TrkH":false,"IsFerryFlight":false,"IsCharterFlight":false,"Sqk":"1512","Ident":false,"Help":false,"Vsi":43,"VsiT":0,"WTC":0,"Species":0,"EngType":0,"EngMount":0,"Mil":false,"Cou":"Bermuda","HasPic":false,"Interested":false,"FlightsCount":0,"Gnd":false,"SpdTyp":0,"CallSus":false,"Trt":2,"Sat":true},

Virtual Radar Server Docs: https://www.virtualradarserver.co.uk/Documentation/Formats/AircraftList.aspx

**Comment by amnesica** [comment]
@Countryman98 We had a look into documentation of VRS. We saw that VRS allows to use multiple feeders and additional data sources. AircraftList.json seems to provide data from all these data sources. A look on your website shows that it works well. So we do not see for what purpose you want to use BelugaProject.

You told us that you have 2 feeders and OpenSky running. What do you see on the BelugaProject map? What are your data sources in this setup? Is it AircraftList.json from VRS or something different? The AircraftList.json from above is not complete, where does it come from? If this AircraftList.json is an input to BelugaProject, it will not work.

Please tell us what is the exact problem you want to solve.

VRS documentation for AircraftList.json says it is required to send all "known aircraft" in subsequent requests to reduce bandwidth. This is not possible with BelugaProject. BelugaProject does not send query parameters, all get requests configured in application.properties are static.

**Comment by Countryman98** [comment]
> @Countryman98 We had a look into documentation of VRS. We saw that VRS allows to use multiple feeders and additional data sources. AircraftList.json seems to provide data from all these data sources. A look on your website shows that it works well. So we do not see for what purpose you want to use BelugaProject.
> 
> You told us that you have 2 feeders and OpenSky running. What do you see on the BelugaProject map? What are your data sources in this setup? Is it AircraftList.json from VRS or something different? The AircraftList.json from above is not complete, where does it come from? If this AircraftList.json is an input to BelugaProject, it will not work.
> 
> Please tell us what is the exact problem you want to solve.
> 
> VRS documentation for AircraftList.json says it is required to send all "known aircraft" in subsequent requests to reduce bandwidth. This is not possible with BelugaProject. BelugaProject does not send query parameters, all get requests configured in application.properties are static.

Hi @amnescica, I Have been looking to replace the VRS frontend for sometime due to it being slow and a little excessive on CPU & Memory. Dont get me wrong VRS is great at handling all the feeders and rebroadcasting them but i am drawn to the modern look and speed of Beluga.

What i was hoping to do was keep VRS as a background system to handle all the connections etc and use Beluga as the front-end website. In doing this i was hoping i could get Beluga to draw feeds from my VRS backend to display on the Beluga frontend (Website). I had a look into Tar1090 but it looked a bit complicated whereas i already have a Beluga test up and running.

**Comment by amnesica** [comment]
@Countryman98 Okay, that draws a clearer picture. All in all we don't think that BelugaProject is the right application for that purpose.

A lot of preprocessing work is needed for all the different formats so that BelugaProject can handle them.

Also: VRS supports a vast amount of attributes which cannot be viewed with the current BelugaProject. Because only some of them are also used by our currently supported feeder is does not make sense to integrate them into the current UI at the moment.

The satellite feeds and the base station format are very interesting but also currently not supported by us.

**Comment by Countryman98** [comment]
@amnesica Okay, was hoping it was going to be as easy as creating another feedmapping config file..
Ohh well, i have a good live Online test up and running (even ssl secured) so i might just continue playing with it and see what i can come up with. That's if you don't mind?

I feel you're sorta directing me away from Beluga but i see Great potential in what you guy's have created :)
All to happy to be a tester for The Beluga Project if required. I'm also a private webhost so know a little bit.. lol
Thanks for your help

**Comment by amnesica** [comment]
VRS is supported in version 4.0.0
