### ISSUE TITLE
Mouse over Details on Airports

### ISSUE THREAD

**Issue by Countryman98** [amnesica/BelugaProject#4]
Just a Suggestion, Also a key: to flight altitude colors and what the different colors markers mean on the map. (Mouseover Airports, Helipads, etc would be great!

Firstly, Please Help me with a feed config for AircraftList.json for Virtual Radar Server.. This will be the decider weather i run with Beluga on my website or not.. Virtual Radar Server has a slightly different AircraftList format that standard.

Devs: I'm sure you could bang this together in no time.
Once again Love the Project, Works great outside the Lan (Fully SSL Secured) just cant move forward without some help here as i;m not in any way a programmer :(

Secondly, Is it possible to turn on trails when an OpenSky Feed?
Thanks Team

**Comment by amnesica** [comment]
@Countryman98 Mouseover airports etc. may come in future versions. An explanantion for the flight altitude colors may come, too. But we do not plan to show trails from Opensky at the moment. I will answer in your other issue about VRS.

**Comment by amnesica** [comment]
FIxed in version 4.0.0
